apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab01-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/dizal8/devops-lab.git
    targetRevision: main
    path: clusters/lab01/applications
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true

  revisionHistoryLimit: 10
