apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
  labels:
    app.kubernetes.io/name: vault-secret-demo
    app.kubernetes.io/part-of: devops-lab
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: vault-auth
            namespace: external-secrets
            audiences:
              - vault
