apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-demo-secret
  namespace: secret-demo
  labels:
    app.kubernetes.io/name: vault-secret-demo
    app.kubernetes.io/part-of: devops-lab
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: vault-demo-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: API_KEY
      remoteRef:
        key: devops-lab/demo
        property: api_key
    - secretKey: ENVIRONMENT
      remoteRef:
        key: devops-lab/demo
        property: environment
